# Generated by Django 5.1.2 on 2024-10-24 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promo',
            name='price_after',
        ),
        migrations.RemoveField(
            model_name='promo',
            name='price_before',
        ),
        migrations.RemoveField(
            model_name='promo',
            name='product',
        ),
        migrations.AddField(
            model_name='promo',
            name='batas_penggunaan',
            field=models.CharField(default='Tidak ada batas', max_length=50),
        ),
    ]
