# Generated by Django 5.1.2 on 2024-12-20 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_image',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='restaurant',
            field=models.CharField(max_length=100),
        ),
    ]
